// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proposal.proto

package dayan_community_srv_proposal

import (
	fmt "fmt"
	idl "github.com/dy-dayan/community-srv-proposal/idl"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewProposalReq struct {
	Title                string   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	Imgs                 []string `protobuf:"bytes,3,rep,name=Imgs,proto3" json:"Imgs,omitempty"`
	Options              []string `protobuf:"bytes,4,rep,name=Options,proto3" json:"Options,omitempty"`
	Creator              int64    `protobuf:"varint,5,opt,name=Creator,proto3" json:"Creator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewProposalReq) Reset()         { *m = NewProposalReq{} }
func (m *NewProposalReq) String() string { return proto.CompactTextString(m) }
func (*NewProposalReq) ProtoMessage()    {}
func (*NewProposalReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3ac5ce23bf32d05, []int{0}
}

func (m *NewProposalReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewProposalReq.Unmarshal(m, b)
}
func (m *NewProposalReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewProposalReq.Marshal(b, m, deterministic)
}
func (m *NewProposalReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewProposalReq.Merge(m, src)
}
func (m *NewProposalReq) XXX_Size() int {
	return xxx_messageInfo_NewProposalReq.Size(m)
}
func (m *NewProposalReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NewProposalReq.DiscardUnknown(m)
}

var xxx_messageInfo_NewProposalReq proto.InternalMessageInfo

func (m *NewProposalReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NewProposalReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *NewProposalReq) GetImgs() []string {
	if m != nil {
		return m.Imgs
	}
	return nil
}

func (m *NewProposalReq) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *NewProposalReq) GetCreator() int64 {
	if m != nil {
		return m.Creator
	}
	return 0
}

type NewProposalResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NewProposalResp) Reset()         { *m = NewProposalResp{} }
func (m *NewProposalResp) String() string { return proto.CompactTextString(m) }
func (*NewProposalResp) ProtoMessage()    {}
func (*NewProposalResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3ac5ce23bf32d05, []int{1}
}

func (m *NewProposalResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewProposalResp.Unmarshal(m, b)
}
func (m *NewProposalResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewProposalResp.Marshal(b, m, deterministic)
}
func (m *NewProposalResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewProposalResp.Merge(m, src)
}
func (m *NewProposalResp) XXX_Size() int {
	return xxx_messageInfo_NewProposalResp.Size(m)
}
func (m *NewProposalResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NewProposalResp.DiscardUnknown(m)
}

var xxx_messageInfo_NewProposalResp proto.InternalMessageInfo

func (m *NewProposalResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type ModifyProposalReq struct {
	ProposalID           string   `protobuf:"bytes,1,opt,name=ProposalID,proto3" json:"ProposalID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	Imgs                 []string `protobuf:"bytes,4,rep,name=Imgs,proto3" json:"Imgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyProposalReq) Reset()         { *m = ModifyProposalReq{} }
func (m *ModifyProposalReq) String() string { return proto.CompactTextString(m) }
func (*ModifyProposalReq) ProtoMessage()    {}
func (*ModifyProposalReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3ac5ce23bf32d05, []int{2}
}

func (m *ModifyProposalReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyProposalReq.Unmarshal(m, b)
}
func (m *ModifyProposalReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyProposalReq.Marshal(b, m, deterministic)
}
func (m *ModifyProposalReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyProposalReq.Merge(m, src)
}
func (m *ModifyProposalReq) XXX_Size() int {
	return xxx_messageInfo_ModifyProposalReq.Size(m)
}
func (m *ModifyProposalReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyProposalReq.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyProposalReq proto.InternalMessageInfo

func (m *ModifyProposalReq) GetProposalID() string {
	if m != nil {
		return m.ProposalID
	}
	return ""
}

func (m *ModifyProposalReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ModifyProposalReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ModifyProposalReq) GetImgs() []string {
	if m != nil {
		return m.Imgs
	}
	return nil
}

type ModifyProposalResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ModifyProposalResp) Reset()         { *m = ModifyProposalResp{} }
func (m *ModifyProposalResp) String() string { return proto.CompactTextString(m) }
func (*ModifyProposalResp) ProtoMessage()    {}
func (*ModifyProposalResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3ac5ce23bf32d05, []int{3}
}

func (m *ModifyProposalResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyProposalResp.Unmarshal(m, b)
}
func (m *ModifyProposalResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyProposalResp.Marshal(b, m, deterministic)
}
func (m *ModifyProposalResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyProposalResp.Merge(m, src)
}
func (m *ModifyProposalResp) XXX_Size() int {
	return xxx_messageInfo_ModifyProposalResp.Size(m)
}
func (m *ModifyProposalResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyProposalResp.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyProposalResp proto.InternalMessageInfo

func (m *ModifyProposalResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type CommentProposalReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentProposalReq) Reset()         { *m = CommentProposalReq{} }
func (m *CommentProposalReq) String() string { return proto.CompactTextString(m) }
func (*CommentProposalReq) ProtoMessage()    {}
func (*CommentProposalReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3ac5ce23bf32d05, []int{4}
}

func (m *CommentProposalReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentProposalReq.Unmarshal(m, b)
}
func (m *CommentProposalReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentProposalReq.Marshal(b, m, deterministic)
}
func (m *CommentProposalReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentProposalReq.Merge(m, src)
}
func (m *CommentProposalReq) XXX_Size() int {
	return xxx_messageInfo_CommentProposalReq.Size(m)
}
func (m *CommentProposalReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentProposalReq.DiscardUnknown(m)
}

var xxx_messageInfo_CommentProposalReq proto.InternalMessageInfo

type CommentProposalResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CommentProposalResp) Reset()         { *m = CommentProposalResp{} }
func (m *CommentProposalResp) String() string { return proto.CompactTextString(m) }
func (*CommentProposalResp) ProtoMessage()    {}
func (*CommentProposalResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3ac5ce23bf32d05, []int{5}
}

func (m *CommentProposalResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentProposalResp.Unmarshal(m, b)
}
func (m *CommentProposalResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentProposalResp.Marshal(b, m, deterministic)
}
func (m *CommentProposalResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentProposalResp.Merge(m, src)
}
func (m *CommentProposalResp) XXX_Size() int {
	return xxx_messageInfo_CommentProposalResp.Size(m)
}
func (m *CommentProposalResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentProposalResp.DiscardUnknown(m)
}

var xxx_messageInfo_CommentProposalResp proto.InternalMessageInfo

func (m *CommentProposalResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type VoteProposalReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteProposalReq) Reset()         { *m = VoteProposalReq{} }
func (m *VoteProposalReq) String() string { return proto.CompactTextString(m) }
func (*VoteProposalReq) ProtoMessage()    {}
func (*VoteProposalReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3ac5ce23bf32d05, []int{6}
}

func (m *VoteProposalReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteProposalReq.Unmarshal(m, b)
}
func (m *VoteProposalReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteProposalReq.Marshal(b, m, deterministic)
}
func (m *VoteProposalReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteProposalReq.Merge(m, src)
}
func (m *VoteProposalReq) XXX_Size() int {
	return xxx_messageInfo_VoteProposalReq.Size(m)
}
func (m *VoteProposalReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteProposalReq.DiscardUnknown(m)
}

var xxx_messageInfo_VoteProposalReq proto.InternalMessageInfo

type VoteProposalResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteProposalResp) Reset()         { *m = VoteProposalResp{} }
func (m *VoteProposalResp) String() string { return proto.CompactTextString(m) }
func (*VoteProposalResp) ProtoMessage()    {}
func (*VoteProposalResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3ac5ce23bf32d05, []int{7}
}

func (m *VoteProposalResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteProposalResp.Unmarshal(m, b)
}
func (m *VoteProposalResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteProposalResp.Marshal(b, m, deterministic)
}
func (m *VoteProposalResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteProposalResp.Merge(m, src)
}
func (m *VoteProposalResp) XXX_Size() int {
	return xxx_messageInfo_VoteProposalResp.Size(m)
}
func (m *VoteProposalResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteProposalResp.DiscardUnknown(m)
}

var xxx_messageInfo_VoteProposalResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*NewProposalReq)(nil), "dayan.community.srv.proposal.NewProposalReq")
	proto.RegisterType((*NewProposalResp)(nil), "dayan.community.srv.proposal.NewProposalResp")
	proto.RegisterType((*ModifyProposalReq)(nil), "dayan.community.srv.proposal.ModifyProposalReq")
	proto.RegisterType((*ModifyProposalResp)(nil), "dayan.community.srv.proposal.ModifyProposalResp")
	proto.RegisterType((*CommentProposalReq)(nil), "dayan.community.srv.proposal.CommentProposalReq")
	proto.RegisterType((*CommentProposalResp)(nil), "dayan.community.srv.proposal.CommentProposalResp")
	proto.RegisterType((*VoteProposalReq)(nil), "dayan.community.srv.proposal.VoteProposalReq")
	proto.RegisterType((*VoteProposalResp)(nil), "dayan.community.srv.proposal.VoteProposalResp")
}

func init() { proto.RegisterFile("proposal.proto", fileDescriptor_c3ac5ce23bf32d05) }

var fileDescriptor_c3ac5ce23bf32d05 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4f, 0x4f, 0xfa, 0x40,
	0x14, 0x4c, 0x29, 0xfc, 0x7e, 0xf0, 0x30, 0x20, 0x4f, 0x0e, 0x4d, 0x63, 0x0c, 0xe9, 0xc1, 0x70,
	0xd0, 0x55, 0xf1, 0x64, 0xa2, 0x17, 0xf1, 0xc2, 0xc1, 0x3f, 0x69, 0x8c, 0xf7, 0x22, 0xab, 0xa9,
	0xa1, 0xdd, 0xb5, 0x6f, 0x85, 0xf0, 0x0d, 0xfc, 0x7c, 0x7e, 0x22, 0xc3, 0x42, 0xa5, 0xa5, 0x0a,
	0xd9, 0xdb, 0xbe, 0xd9, 0xd9, 0xe9, 0xcc, 0xec, 0x16, 0x1a, 0x32, 0x11, 0x52, 0x50, 0x30, 0x66,
	0x32, 0x11, 0x4a, 0xe0, 0xfe, 0x28, 0x98, 0x05, 0x31, 0x7b, 0x16, 0x51, 0xf4, 0x11, 0x87, 0x6a,
	0xc6, 0x28, 0x99, 0xb0, 0x94, 0xe3, 0xc2, 0x30, 0x20, 0xbe, 0x60, 0x7a, 0x9f, 0x16, 0x34, 0xee,
	0xf8, 0xf4, 0x61, 0xb9, 0xe7, 0xf3, 0x77, 0x6c, 0x43, 0xe5, 0x31, 0x54, 0x63, 0xee, 0x58, 0x1d,
	0xab, 0x5b, 0xf3, 0x17, 0x03, 0x3a, 0xf0, 0xbf, 0x2f, 0x62, 0xc5, 0x63, 0xe5, 0x94, 0x34, 0x9e,
	0x8e, 0x88, 0x50, 0x1e, 0x44, 0xaf, 0xe4, 0xd8, 0x1d, 0xbb, 0x5b, 0xf3, 0xf5, 0x7a, 0xce, 0xbe,
	0x97, 0x2a, 0x14, 0x31, 0x39, 0x65, 0x0d, 0xa7, 0xa3, 0xd6, 0x49, 0x78, 0xa0, 0x44, 0xe2, 0x54,
	0x3a, 0x56, 0xd7, 0xf6, 0xd3, 0xd1, 0xbb, 0x80, 0x66, 0xce, 0x09, 0x49, 0x3c, 0x84, 0xea, 0x75,
	0x40, 0x7c, 0xbe, 0xd6, 0x6e, 0xea, 0x3d, 0x60, 0xda, 0xfc, 0x1c, 0xf1, 0x7f, 0xf6, 0xbc, 0x29,
	0xb4, 0x6e, 0xc5, 0x28, 0x7c, 0x99, 0x65, 0x73, 0x1c, 0x00, 0xa4, 0xe3, 0xe0, 0x66, 0x19, 0x26,
	0x83, 0xac, 0x72, 0x96, 0xfe, 0xc8, 0x69, 0xff, 0x9e, 0xb3, 0xbc, 0xca, 0xe9, 0x5d, 0x02, 0xae,
	0x7f, 0xd8, 0xc0, 0x76, 0x1b, 0xb0, 0x2f, 0xa2, 0x88, 0xc7, 0x2a, 0xe3, 0xdb, 0xbb, 0x82, 0xbd,
	0x02, 0x6a, 0x20, 0xda, 0x82, 0xe6, 0x93, 0x50, 0x3c, 0xab, 0x88, 0xb0, 0x9b, 0x87, 0x48, 0xf6,
	0xbe, 0x6c, 0xa8, 0xa6, 0x00, 0xbe, 0x41, 0x3d, 0x53, 0x3d, 0x1e, 0xb1, 0x4d, 0xef, 0x87, 0xe5,
	0xdf, 0x8b, 0x7b, 0x6c, 0xc0, 0x26, 0x89, 0x04, 0x8d, 0x7c, 0x65, 0x78, 0xb2, 0x59, 0xa0, 0x70,
	0xb3, 0xee, 0xa9, 0xd9, 0x01, 0x92, 0x38, 0x81, 0xe6, 0x5a, 0xa7, 0xb8, 0x45, 0xa4, 0x78, 0x31,
	0xee, 0x99, 0xe1, 0x09, 0x92, 0x18, 0xc1, 0x4e, 0xb6, 0x79, 0xdc, 0xd2, 0xd5, 0xda, 0xc5, 0xb9,
	0xcc, 0x84, 0x4e, 0x72, 0xf8, 0x4f, 0xff, 0xd4, 0xe7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x93,
	0x61, 0xec, 0x6a, 0x10, 0x04, 0x00, 0x00,
}
